import generated from './generated/metadata.json'
import type { Example, LibraryRamp, Schema } from './types'
import type { DistanceNode } from './gpu/geometry'

export interface EditorMetadata {
  assetVersion: number
  documentVersion: number
  schema: Schema
  examples: Example[]
  ramps: LibraryRamp[]
  shapes: { id: string; label: string; solid: DistanceNode }[]
  version2WrappingLibraryRamps: string[]
}
// Generated by Haskell; the reference suite verifies every field against source.
const metadata = generated as unknown as EditorMetadata
if (metadata.assetVersion !== 1 || metadata.documentVersion !== 4) throw new Error('Unsupported editor metadata version')
export default metadata
